// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdamgeerddbblnqdongf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kYW1nZWVyZGRiYmxucWRvbmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NjM2NzksImV4cCI6MjA1NDIzOTY3OX0.OJd5B4RaKH4S-slqpNIMhvv9GSRp4qg5bxrwjuiW3ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);